
package safedata;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolicyService", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolicyService {


    /**
     * 
     * @param id
     * @return
     *     returns safedata.Policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolicyById", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyById")
    @ResponseWrapper(localName = "getPolicyByIdResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyByIdResponse")
    public Policy getPolicyById(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policyID
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePolicyById", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DeletePolicyById")
    @ResponseWrapper(localName = "deletePolicyByIdResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DeletePolicyByIdResponse")
    public void deletePolicyById(
        @WebParam(name = "policyID", targetNamespace = "")
        String policyID)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updatePolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.UpdatePolicy")
    @ResponseWrapper(localName = "updatePolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.UpdatePolicyResponse")
    public void updatePolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enablePolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.EnablePolicy")
    @ResponseWrapper(localName = "enablePolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.EnablePolicyResponse")
    public void enablePolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policy
     * @return
     *     returns safedata.Policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.CreatePolicy")
    @ResponseWrapper(localName = "createPolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.CreatePolicyResponse")
    public Policy createPolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception
    ;

    /**
     * 
     * @param password
     * @param policy
     * @return
     *     returns safedata.TaskExecutionContext
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runDiskSafeVerification", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunDiskSafeVerification")
    @ResponseWrapper(localName = "runDiskSafeVerificationResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunDiskSafeVerificationResponse")
    public TaskExecutionContext runDiskSafeVerification(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DeletePolicy")
    @ResponseWrapper(localName = "deletePolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DeletePolicyResponse")
    public void deletePolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param disksafe
     * @return
     *     returns safedata.Policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolicyByDiskSafe", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyByDiskSafe")
    @ResponseWrapper(localName = "getPolicyByDiskSafeResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyByDiskSafeResponse")
    public Policy getPolicyByDiskSafe(
        @WebParam(name = "disksafe", targetNamespace = "")
        DiskSafe disksafe)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "disablePolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DisablePolicy")
    @ResponseWrapper(localName = "disablePolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.DisablePolicyResponse")
    public void disablePolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns safedata.Policy
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolicyByDiskSafeId", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyByDiskSafeId")
    @ResponseWrapper(localName = "getPolicyByDiskSafeIdResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyByDiskSafeIdResponse")
    public Policy getPolicyByDiskSafeId(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param policyID
     * @return
     *     returns safedata.TaskExecutionContext
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runPolicyByID", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunPolicyByID")
    @ResponseWrapper(localName = "runPolicyByIDResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunPolicyByIDResponse")
    public TaskExecutionContext runPolicyByID(
        @WebParam(name = "policyID", targetNamespace = "")
        String policyID)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolicyIDs", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyIDs")
    @ResponseWrapper(localName = "getPolicyIDsResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicyIDsResponse")
    public List<String> getPolicyIDs();

    /**
     * 
     * @param policy
     * @return
     *     returns safedata.TaskExecutionContext
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runPolicy", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunPolicy")
    @ResponseWrapper(localName = "runPolicyResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunPolicyResponse")
    public TaskExecutionContext runPolicy(
        @WebParam(name = "policy", targetNamespace = "")
        Policy policy)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param password
     * @param policyID
     * @return
     *     returns safedata.TaskExecutionContext
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runDiskSafeVerificationByPolicyID", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunDiskSafeVerificationByPolicyID")
    @ResponseWrapper(localName = "runDiskSafeVerificationByPolicyIDResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RunDiskSafeVerificationByPolicyIDResponse")
    public TaskExecutionContext runDiskSafeVerificationByPolicyID(
        @WebParam(name = "policyID", targetNamespace = "")
        String policyID,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @param diskSafeID
     * @throws AccessControlFault_Exception
     * @throws OperationFailedFault_Exception
     * @throws UnknownObjectFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "refreshPolicyFromDiskSafe", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RefreshPolicyFromDiskSafe")
    @ResponseWrapper(localName = "refreshPolicyFromDiskSafeResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.RefreshPolicyFromDiskSafeResponse")
    public void refreshPolicyFromDiskSafe(
        @WebParam(name = "diskSafeID", targetNamespace = "")
        String diskSafeID)
        throws AccessControlFault_Exception, OperationFailedFault_Exception, UnknownObjectFault_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<safedata.Policy>
     * @throws OperationFailedFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPolicies", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPolicies")
    @ResponseWrapper(localName = "getPoliciesResponse", targetNamespace = "http://policy.apiV2.server.backup.r1soft.com/", className = "safedata.GetPoliciesResponse")
    public List<Policy> getPolicies()
        throws OperationFailedFault_Exception
    ;

}
